### ISSUE TITLE
[BACK] Criar tratador de requisições que invoca o compilador e responde com a saída

### ISSUE THREAD

**Issue by concatto** [concatto/repositorio-exercicios#5]
Criar um método que recebe o código fonte, invoca o compilador e responde com a saída. Lembrar que pode dar errado (a compilação)

**Comment by concatto** [comment]
COMMITERSON `7f8b0ed6831baba4012b6fc367a5cb20bb4bc346`

**Comment by concatto** [comment]
Criar tratadores de requisição HTTP

**Comment by eliel-jr** [comment]
editar segundo exercicio, para algo mais simples sem utilzação de vetores e matrizes
